### ISSUE TITLE
File 'json/vault.json' was not found

### ISSUE THREAD

**Issue by jaimelaborda** [ast-astik/bitwarden-json-reader#1]
I just downloaded the source code and opened de index.html file and this message appears:

![image](https://github.com/user-attachments/assets/a86327f2-1304-40e4-af34-f668e766f62c)

In the json folder, there is a vault.json file as an example that is the same one you are running on your demo environment. What am I doing wrong?

Thanks

**Comment by astik-dev** [comment]
Hi @jaimelaborda  !
It looks like you opened the HTML file directly using the file protocol. To ensure that `vault.json` loads correctly, please set up a local server and access the files through `http://localhost`. This will allow the application to function properly.
